### ISSUE TITLE
niejasne: albo w całej karierze, albo przez 9 lat

### ISSUE THREAD

**Issue by michaldo** [emkael/pzbs-ranking#12]
https://github.com/emkael/pzbs-ranking/blob/bed86ebbea1c1d7047f35966399c28529dde3f92/static/metoda.html#L30

**Comment by emkael** [comment]
Niestety, nie jestem w stanie pomóc, bo nie znam szczegółów wyliczania wartości rankingu.

Ten projekt obejmuje tylko prezentację gotowych danych, za którą jestem odpowiedzialny.

Jestem natomiast pewien, że mail do Prezesa Stachnika, który układa zasady klasyfikacji zawodników (w.stachnik@pzbs.pl), pozwoli wyjaśnić wątpliwości i przeredagować treści na stronie, eliminując niejasności.
