### ISSUE TITLE
One link to rank them all

### ISSUE THREAD

**Issue by Jaom** [emkael/pzbs-ranking#13]
Jeden link:
`http://ranking.pzbs.pl/current_ranking.csv`
który pozwala pobierać zawsze aktualny CSV z rankingiem, zawsze w tym samym formacie.

Przeznaczenie:
integracja z 3rd party apps

**Comment by emkael** [comment]
Dla każdego notowania zdefiniowano przekierowania do plików CSV i JSON (mogą być przydatniejsze dla aplikacji niż CSV). Zakładając, że URL do notowania to `ranking.pzbs.pl/PREFIX.html` (przy czym `PREFIX` to może być również `index` dla aktualnego notowania):
 * `ranking.pzbs.pl/PREFIX.csv` przekierowuje do CSV na githubie (tego, który jest linkowany w stopce)
 * `ranking.pzbs.pl/PREFIX.json` przekierowuje do pełnego JSONa z danymi (tego, który jest wciągany przez stronę notowania)
 * `ranking.pzbs.pl/PREFIX.minimal.json` przekierowuje do kompaktowego JSONa z danymi (słownika indeksowanego PIDami, zawierającego tylko pozycje i punkty dla każdego PIDu)

Lada moment będzie na ranking.pzbs.pl, wrzucę informację do trackera TC.
