### ISSUE TITLE
Nice to have setup paging size and on/off paging

### ISSUE THREAD

**Issue by michaldo** [emkael/pzbs-ranking#8]
Actually it is impossible to see more than 40 entries at the same time

**Comment by emkael** [comment]
Custom paging (a dropdown with the default 50, 100, 200, 500 and all 1000 per page) has been added.

**Comment by michaldo** [comment]
Immediate deploy to PZBS, great

However, I have small notice. If page size changes, drop down jumps betwen center and right, because number of pages changes (technically, div id="top-paginator" changes width)
Usually, in such case dropdown is right aligned

**Comment by emkael** [comment]
Page size settings panel is now always pulling to the right, while the top pagination panel is pulling to the left. The bottom pagination remains centered.
